services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_NAME
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - DATABASE_HOST
      - DATABASE_PORT
    volumes:
      - .:/app
      - /app/node_modules

  database:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
   
volumes:
  db_data:
